profiles/urls.py
from django.contrib import admin
from django.urls import path
from profiles import views
from .views import ProfileListView,ProfileDetailView # , follow_unfollow_profile


app_name='profiles'

urlpatterns = [
    path('', views.index, name='index'),
    # path('profileview/', views.my_profile_view, name='profileView'),
    path('profileview/', views.my_profile_api, name='profileView'),
    path('profileviewapi/', views.myprofile_apimethod, name='profileViewApi'),
    path('profileupdateapi/', views.update_profileApi, name='profileUpdateApi'),
    
    path('profilelistview/', ProfileListView.as_view(), name='profilelistview'),
    # path('hh/<pk>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('hh/<pk>/', views.ProfileDetailView, name='profile-detail-view'),
    # path('switchfollow', views.follow_unfollow_profile, name='follow_unfollow_view'),
    path('profiletlist/<int:pk>/', views.profile_list, name='profilelist'),
    path('fetch/', views.fetch, name='fetch'),
    path('postapicall/', views.post, name='post'),
    path('postapi/', views.postapi, name='post-api'),
    path('detailapi/', views.DetailProfileApi, name='detail-api'),
    ]

to/urls.py
"""
Definition of urls for app
"""

from datetime import datetime
from django.urls import path,include 
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import views
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header="fahad app Admin"
admin.site.site_title="fahad app Admin portal"
admin.site.index_title="wellcome to my app"



urlpatterns = [
    path('', include('profiles.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    # path("contact", views.kontact, name='contact'),
    # path("about", views.abot, name='about')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields.related import RelatedField
from django.utils import timezone
from .utils import get_random_code
from django.template.defaultfilters import slugify

class profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    following = models.ManyToManyField(User, related_name='following', blank=True)
    followers = models.ManyToManyField(User, related_name='follower', blank=True)


    bio = models.TextField(default="no bio...",max_length=300)
    email = models.EmailField(blank=True,max_length=200)
    country = models.TextField(blank=True,max_length=200, default='Pakistan')
    avatar = models.ImageField(default='avatar.png',upload_to='avatars/')
    # friends = models.ManyToManyField(User,blank=True,related_name='firends')
    slug = models.SlugField(unique=True , blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    # ---------new------------
    def profile_posts(self):
        return self.post_set.all()
    class Meta:
        ordering = ('-created',)

   

    def get_following(self):
        return self.following.all()
    
    def get_followers(self):
        return self.followers.all()


    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"

    def save(self, *args, **kwargs):
        ex = False
        if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                ex = profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_code()))
                    ex = profile.objects.filter(slug=to_slug).exists()
        else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs) 



STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)

class Relationship(models.Model):
    sender = models.ForeignKey(profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    # is_active = models.BooleanField(label='Active?')
    

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

profiles/forms.py
from django import forms 
from .models import profile
from django.contrib.auth.models import User

class ProfileForm(forms.ModelForm):
   
    class Meta:
        model = profile 
        fields = [ 
            'first_name',
            'last_name',
            'bio',
            'email',
            'country',
            'avatar',
        
            

        ] 

profiles/views.py
from django.shortcuts import render,redirect
from requests.api import request
from rest_framework.parsers import JSONParser
from rest_framework import status
from rest_framework.response import Response
from rest_framework.serializers import ListSerializer
from .models import profile
from .forms import ProfileForm
from django.views.generic import ListView,DetailView, detail
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from django.http.response import HttpResponse, JsonResponse
from .serializers import ProfileSerializer,ProfileUpdateSerializer
import json
import requests
from rest_framework.decorators import api_view
from django.contrib import messages

def index(request):
    return render(request,'index.html')

#  converted to API call so commented this

# def follow_unfollow_profile(request):
#     if request.method=="POST":
#         my_profile=profile.objects.get(user=request.user)
#         pk= request.POST.get('profile_pk')
#         obj = profile.objects.get(pk=pk)
#         # newly added 
#         if my_profile.user in obj.followers.all():
#             obj.followers.remove(my_profile.user)
#         else:
#             obj.followers.add(my_profile.user)


#         if obj.user in my_profile.following.all():
#             my_profile.following.remove(obj.user)
#         else:
#             my_profile.following.add(obj.user)
#         return redirect(request.META.get('HTTP_REFERER'))
#     return redirect('profiles:profilelistView')



# new follow unfollow thourgh API
    # posting data to api and getting the result as json response
        #post Api call
def post(request):
    if request.method=="POST":
        my_profile=profile.objects.get(user=request.user)
        pk= request.POST.get('profile_pk')
        obj = profile.objects.get(pk=pk)
        body={
            'myprofile':my_profile.user.id,
            'userobj' : obj.user.id,
        }
        result=requests.post('http://127.0.0.1:8000/postapi/',data=body)
        print("---------------------------------------")
        print(result.status_code)
        if result.status_code == 200:
            messages.success(request, 'Api call is working pefectly fine : Action Successful')
        else:
            messages.success(request, 'Api call is not working fine')

        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:profilelistView')

# post APi method
@csrf_exempt
@api_view(['POST'])
def postapi(request):
    if request.method=="POST":
        followerid=request.POST.get('myprofile')
        followedid=request.POST.get('userobj')
        followerobj = profile.objects.get(user=followerid)
        followedobj = profile.objects.get(user=followedid)
        # print(request.POST.get())
        # following=request.POST.get('myprofile')
        # followed=request.POST.get('userobj')
        if followerobj.user in followedobj.followers.all():
            followedobj.followers.remove(followerobj.user) 
        else:
            followedobj.followers.add(followerobj.user)


        if followedobj.user in followerobj.following.all():
            followerobj.following.remove(followedobj.user)
        else:
            followerobj.following.add(followedobj.user)
        print("===============================")
        
        return (Response(status= status.HTTP_200_OK))
    else:
        return Response(status= status.HTTP_500_INTERNAL_SERVER_ERROR)


# def my_profile_view(request):
#     print(request.user)
#     obj= profile.objects.get(user=request.user)
#     form= ProfileForm()
#     context={

#         'obj': obj,
#         'form': form,

#     }
    
#     return render(request,'myprofile.html',context)

# ---------new--------------Currently displaying data
class ProfileListView(ListView): 
    model =profile
    template_name = 'main.html'
    context_object_name='profiles'
    def get_queryset(self):
        return profile.objects.all().exclude(user=self.request.user)
       

# _-------------------new for api end point----

@api_view(['GET'])
def profile_list(request,pk):
    list = profile.objects.all().exclude(user_id=pk)   
    list_serializer =ProfileSerializer(list,many=True)
    print(list_serializer.data)
    return Response(list_serializer.data)
    # return JsonResponse(list_serializer.data, safe=False)

def fetch(request):
   pk=request.user.id
   res=requests.get('http://127.0.0.1:8000/profiletlist/'+str(pk)+'/')
   datastr = json.loads(res.text)
#    print(datastr)
#    datastr=json.dumps(data)
   print(type(datastr))
   context = {
       'strdata': datastr,
   }
   return render(request,'jsonrenderer.html',context)
       




# getting the detailed view of selected profile
# class ProfileDetailView(DetailView):
#     model=profile
#     template_name ='detail.html'
#     # getting object of the current selected profile
#     def get_object(self, **kwargs):
#         pk =self.kwargs.get('pk')
#         # getting the profile
#         view_profile = profile.objects.get(pk=pk)
#         return view_profile

#     #  function for passing some variables to tamplate
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         # getting profiles and passing them
#         # selected profikle
#         view_profile = self.get_object()
#         # my profile 
#         my_profile= profile.objects.get(user=self.request.user)
#         if view_profile.user in my_profile.following.all():
#             follow=True
#         else:
#             follow=False

#         context["follow"]=follow
#         return context

    
# profile detail view following or not check(to show button differently)
    # api call

def ProfileDetailView(request, pk):
    data={

        'viewprofileid' :  pk,
        'myprofileid'   : request.user.id
    }
    # check if already follow or not
    result=requests.get('http://127.0.0.1:8000/detailapi/',params=data)
    result = json.loads(result.text)

    
    view_profile = profile.objects.get(pk=pk)
    
    context={
        'follow': result['follow'],
        'object' : view_profile
    }
    
    return render(request,'detail.html',context)
    


# profile detail view api method
@api_view(['GET'])
def DetailProfileApi(request):
    view_profile = profile.objects.get(pk=request.GET.get('viewprofileid'))
    my_profile= profile.objects.get(user=request.GET.get('myprofileid'))

    if view_profile.user in my_profile.following.all():
            follow={'follow': True}
    else:
            follow={'follow': False}
    return Response(follow)







# def my_profile_view(request):
#     obj = profile.objects.get(user=request.user)
#     form = ProfileForm(request.POST or None, request.FILES or None, instance=obj)
#     confirm = False

#     if request.method == 'POST':
#         if form.is_valid():
#             form.save()
#             confirm = True

#     context = {
#         'obj': obj,
#         'form': form,
#         'confirm': confirm,
#     }

#     return render(request, 'myprofile.html', context)

# my_profile_view Api call
@csrf_exempt
def my_profile_api(request):
    profile_id=request.user.id
    data={
        'id':profile_id
    }
    res=requests.get('http://127.0.0.1:8000/profileviewapi/', data)
    result=json.loads(res.text)
    print(type(result))
    serialzer=ProfileSerializer(result["obj"])
    result["serializer"]=serialzer
    
#     context = {
#        'strdata':result, # result is a list of dictionary
#    }
    return render(request, 'myprofile.html',result)

# myprofile Api method
@csrf_exempt
@api_view(['GET'])
def myprofile_apimethod(request):
    user_id = request.GET.get('id')
    # obj = profile.objects.get(user__id=user_id)
    
    # print(obj.first_name,obj.last_name,obj.email)
    # form = ProfileForm(request.POST or None, request.FILES or None, instance=obj)
    confirm = False

    # if request.method == 'POST':
    #     if form.is_valid():
    #         form.save()
    #         confirm = True  
    new_obj =  profile.objects.filter(user__id=user_id)
    
    obj_serializer =ProfileSerializer(new_obj, many=True)
    # print(obj_serializer.)
    
    context = {
         'obj': obj_serializer.data,
        'confirm': confirm,
    }
    
    return Response(context)

@csrf_exempt
@api_view(['POST'])
def update_profileApi(request):
    user_id = request.POST.get('id')
    new_obj =  profile.objects.filter(user_id=user_id).first()
    confirm = False
    if request.method == 'POST':
        print(">>>>>>>>>>>>>>>>>>>>>>>>")
        print(request.data)
        serializer = ProfileUpdateSerializer(new_obj,data=request.data, partial=True)
        
        if serializer.is_valid(): 
            serializer.save()
            print(":::::::::::::::::::::::::")
        else:
            print(serializer.errors)
    return Response({'confirm':confirm})

profiles/templates/base1.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Bootstrap js -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!--sementic ui import--> 
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
      <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>

    
    <title>Argon Social</title>
  </head>
  <body>

    {% comment %} navbar {% endcomment %}

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" 
        {% if user.is_authenticated %}
        href="{% url 'posts-follow-view' %}"
        {% else %}
        href="{% url 'profiles:index' %}"
        {% endif %}
        >Argon Social</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
         
           
          <li class="nav-item">
          <a class="nav-link" href="/profileview">Profile</a>
          </li> 
         
          <li class="nav-item">
          <a class="nav-link" href="/posts/">Feed</a>
          </li> 
          <li class="nav-item">
            <a class="nav-link" href="/profilelistview">People</a>
            </li> 
            <li class="nav-item">
            <a class="nav-link" href="/profiletlist">profilelist</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/fetch">fetch</a>
              </li>
          <li class="nav-item">
          <a class="nav-link" href="/accounts/login/">login</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="/accounts/logout/">logout</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        </div>
      </div>
      </nav>
    
     
    {% block content %}
    {% endblock content%}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

profiles/templates/detail.html
{% extends 'base1.html'%}
{% block title%}
Profile detail
{% endblock title%}

{% block content%}

<!-- For  follow the user-->

 <!-- Modal -->
 <div class="modal fade bd-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"  width: 90%; margin: 300px;>
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
    
                <h3>By clicking yes you will see all the posts published by  <strong>{{object.first_name}}</strong> </h3>
            
              <div class="actions">
                  <form action="{% url 'profiles:post' %}" method='POST'>
                      {% csrf_token%}
                  <input type='hidden' name ='profile_pk' value={{object.pk}}>
                  <button type="submit" class="ui green ok button">
                      <i class="checkmark icon"></i>
                      Yes
                  </button>
                  </form>
              </div>
        </div>
    </div>
</div>







 <!-- For un follow the user-->

   <div class ="ui grid" style="margin:50px">
    <div class ="row">
        {% if messages %}
        {% for message in messages %}
        <div class="ui green message">{{message}}</div>
        {% endfor %} 
        {% endif %}

        <div class="four wide column">
            <img src="{{object.avatar.url}}" width="200" height="230">
            <h1>{{object.first_name}}</h1>
        </div>
        <hr>
        {{follow}}
        {% if follow%}
         <form action="{% url 'profiles:post' %}" method="POST">
             {% csrf_token%}
             <input type='hidden' name ='profile_pk' value={{object.pk}}>
             <button type="submit" class="ui negative button">Unfollow</button>
         </form>
         {% else %}
          <!-- Button trigger modal -->
            <button type="button" class="ui positive button" data-toggle="modal" data-target="#exampleModal">Follow</button>
     
        {% endif %}

        <div class="twelve wide column">
            {% for post in object.profiles_posts%}
            <div class="ui segment">
                {{post.body}}  
            </div>
            {% endfor %}
        </div>
  <!--it means that we  no specify the name of object for context passing so used object word-->
 
{% endblock content%}

profiles/templates/index.html
{% extends 'base1.html'%}
{% block content%}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-10 col-sm-12 text-center">
            <h1 class="display-2">Connect With Your Friends</h1>
            <p class="mt-3 lead">Follow people who interest you, stay up to date on the latest news and join conversations with your friends!</p>
            <div class="d-flex justify-content-center mt-5">
                <a href="{% url 'account_login' %}" class="btn btn-light mr-2">Log In</a>
                <a href="{% url 'account_signup' %}" class="btn btn-dark">Register</a>
            </div>
        </div>
    </div>
</div>

{%  endblock content%}

profiles/templates/jsonrenderer.html
{% extends 'base1.html'%}
{% block content%}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-10 col-sm-12 text-center">
        {% for data in strdata%}
            {{data.first_name}}
            <br>
            {% endfor%}
            </div>
        </div>
    </div>
</div>

{%  endblock content%}

profiles/templates/main.html
{% extends 'base1.html'%}
{% block title%}
Profiles new page
{% endblock title%}
{% block content%}

        <h1 > Profiles</h1>
        {% for profile in profiles%}
        <div class="ui segment" style="margin: 50px;">
        {{profile}}
        <br>
        <a href={% url 'profiles:profile-detail-view' profile.pk%}>
        <button type="button" class="btn btn-primary">See Profiles</button>
        </a>
        </div>
    
{% endfor%}
{% endblock content%}

profiles/templates/myprofile.html
{% extends 'base1.html'%}
{% load rest_framework %}
{% block title%}
Profiles
{% endblock title%}

{% block content%}

  
  <!-- Modal -->
  <div class="modal fade bd-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"  width: 90%; margin: 300px;>
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
        <div class="row justify-content-center mt-3">
            <div class="col-md-10 col-sm-12 ">
                <div class="header">
                    <h3><strong>Update your Profile </strong></h3>
                  </div>
                <div class="image content">
                    <div class="ui medium image">
                        {% for data in obj%}
                    
                        <img src="{{data.avatar}}" width="200" height="230">
                        {% endfor %}
                    </div>
                    <div class="description">
                        <div class="ui header">Provide some additional/newest info about you </div>
                
                    <form action="/profileupdateapi/" method="POST" class="ui form" enctype='multipart/form-data' >
                        {% csrf_token %}

                        <input value='{{request.user.id}}' name="user" id='user'>
                    
                        {% render_form serializer %}
                        
                        <input type="submit" value="Save">
                        <!--{{form.as_p}}-->
                        
                    <div class="form-row">
                            <div class="form-group col-md-6">
                              <label for="inputFName">First Name</label>
                              <input type="text" class="form-control" id="fname" placeholder="e.g Muhammad">
                            </div>
                        <div class="form-group col-md-6">
                            <label for="inputLName">Last Name</label>
                            <input type="text" class="form-control" id="lname" placeholder="e.g Abdullah">
                            </div>
                        </div>
                          <div class="form-group col-md-6">
                            <label for="inputBio">Bio</label>
                            <input type="text" class="form-control" id="bio" placeholder="Sample Bio">
                          </div>
                          
                          <div class="form-row">
                            <div class="form-group col-md-6">
                              <label for="inputCity">Country</label>
                              <input type="text" class="form-control" id="country">
                            </div>

                          </div>
                          <div class="form-group">
                            <div class="form-group">
                                <label for="exampleFormControlFile1">update your picture</label>
                                <input type="file" class="form-control-file" id="pic">
                              </div>
                          </div>

                        
                    
                    </div>
                </div>
                <div class="actions">
                  <button type='submit' class="ui positive right labeled icon button">
                    Update
                    <i class="checkmark icon"></i>
                  </button>
                  <br><br>
                  </form>
                
                </div>

            </div>
        </div>
             

            </div>
        </div>
  </div>





<!-- View of profile -->
  <div class="row justify-content-center mt-3">
    <div class="col-md-5 col-sm-12 ">
        {% for message in messages %}
            {{message}}
        {% endfor %}
        
        {% if confirm %}
            <div class="ui green message">Your profile has been updated</div>
        {% endif %}
        <h3>User Name : {{request.user}}</h3>
        <div class="ui grid">
            <div class='row'>
               
                <div class='six wide column'>
                    {% for data in obj%}
                    <img class="ui medium rounded image" width="200" height="230" src={{data.avatar}}>
                    {% endfor %}
                    <div class="row mt-5">
                        <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Update Your Profile</button>
                    </div>
                </div>
                
                
                <div class="ten wide column">
                    <table class="ui table">
                        <tbody>
                            {% for data in obj%}
                
                            <tr>
                                <td>username</td>
                                <td>{{user}}</td>
                            </tr>
                            <tr>
                                <td>first name</td>
                                <td>{{data.first_name}}</td>
                            </tr>
                            <tr>
                                <td>last name</td>
                                <td>{{data.last_name}}</td>
                            </tr>
                            <tr>
                                <td>bio</td>
                                <td>{{data.bio}}</td>
                            </tr>
                            <tr>
                                <td>country</td>
                                <td>{{data.country}}</td>
                            </tr>
        

                            <tr>
                                <td>Followers</td>
                                <td>
                                    <ul>
                                        {% for follower in data.followers %}
                                            <li>{{follower.username}}</li>
                                        {% endfor %}
                                    </ul>
                                </td>
                            </tr>
                            <tr>
                                <td>Following</td>
                                <td>
                                    <ul>
                                        {% for followin in data.following %}
                                            <li>{{followin.username}}</li>
                                        {% endfor %}
                                    </ul>
                                </td>
                            </tr>
                            {% endfor%}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>




{% comment %} <script type="text/javascript"> 
     $(document).ready(function(){ 
        
    $('#mybtn').click(function(){
        console.log("clickeeeeeeeeeeedd")
        $('#mymodal').modal('show');
    })
}) 
</script> {% endcomment %}

{% endblock content%}

profiles/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container-fluid">
	  <a class="navbar-brand" href="#">Argon Social</a>
	  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav me-auto mb-2 mb-lg-0">
		
		 
			 
		  <li class="nav-item">
			<a class="nav-link" href="#">Profile</a>
		  </li> 
		 
		  <li class="nav-item">
			<a class="nav-link" href="#">Feed</a>
		  </li> 
		  <li class="nav-item">
			<a class="nav-link" href="/accounts/login/">login</a>
		  </li>
			<li class="nav-item">
			<a class="nav-link" href="/accounts/logout/">logout</a>
		  </li>
		</ul>
		<form class="d-flex">
		  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
		  <button class="btn btn-outline-success" type="submit">Search</button>
		</form>
	  </div>
	</div>
  </nav>